version: '3.3'

services:
    rabbitmq:
        container_name: rabbitmq
        image: 'rabbitmq:3-management'

        ports:
            - '5672:5672'
            - '8080:15672'

        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
        restart: always
        privileged: true


    reseiver:
        container_name: reseiver
        build: reseiver/
        network_mode: host
        depends_on:
            - rabbitmq

        restart: on-failure
        entrypoint: python reseiver.py


    sender:
        container_name: sender
        build: sender/
        ports:
            - 8000:8000
        depends_on:
            - rabbitmq
            - reseiver
        restart: on-failure
        entrypoint: uvicorn app:app --host 0.0.0.0 --port 8000



